### ISSUE TITLE
Conflict with gpytorch 1.5.1

### ISSUE THREAD

**Issue by CY-Zhang** [nion-software/nionswift#744] opened 2021-10-16 01:38 UTC
On the windows system that connects to a Nion microscope, there is a conflict between Nion Swift and gpytorch 1.5.1. (https://gpytorch.ai/) Whenever I import gpytorch in the python console of Swift, Swift would freeze and has to be closed. Meanwhile, I do not see any error message on the python console that runs Swift.

I don't have any issue import gpytorch from an anaconda console of the same environment that runs the Swift. I also have no problem import gpytorch from the python console Swift on my personal computer that runs a Linux system. Here is a list of all the Nion related packages installed on the computer connected to the instrument and my personal computer.

| Package Name| Nion microscope computer | My desktop |
| ------------- | ------------- |--------------|
| nion-alignment | 0.2.0 | NA |
| Nion-Hardware | 1.3.2 | NA |
| niondata | 0.13.14 | 0.13.15 |
| nionswift | 0.15.6 | 0.15.7 |
| nionswift-eels-analysis | 0.5.3 | 0.5.4 |
| nionswift-experimental | 0.7.1 | 0.7.2 |
| nionswift-instrumentation | 0.19.5 | 0.19.5 |
| nionswift-io | 0.14.3 | 0.14.3 |
| nionswift-tool | 0.4.10 | 0.4.13 |
| nionswift-video-capture | 0.1.0 | 0.1.0 |
| nionui | 0.5.1 | 0.5.2 |
| niontuils | 0.3.26 | 0.3.26 |

Most package versions are very close between the Nion microscope computer and my desktop, except 1. I don't have nion-alignment and Nion-Hardware installed, 2. I'm using a Linux system. I will test on a Windows computer and see if I can reproduce this problem. I will keep this issue updated, and please feel free to suggest any other tests I can do. Thanks!

**Comment by cmeyer** [comment] 2021-10-16 01:49
A few questions: What version of Python (3.8, 3.9) are you running on your computer? What package manager (Anaconda, conda-forge, PyPI, etc.)? And what version of Linux (Ubuntu 18.04, etc.)? Also, is everything in the environment updated (particularly: numpy 1.21 and scipy 1.7.1)?

Often these problems are caused by an installation that required an incompatible downgrade due to a secondary requirement (e.g. opencv is often.a culprit) that the package manager didn't catch. If you install from scratch into a new conda environment or venv, do you still get the problem?

**Comment by CY-Zhang** [comment] 2021-10-16 04:19
> A few questions: What version of Python (3.8, 3.9) are you running on your computer? What package manager (Anaconda, conda-forge, PyPI, etc.)? And what version of Linux (Ubuntu 18.04, etc.)? Also, is everything in the environment updated (particularly: numpy 1.21 and scipy 1.7.1)?
> 
My computer runs Python 3.8, I used PyPI as the package manager, and the Linux version is Ubuntu 20.01. Both numpy and scipy are updated (numpy 1.21.2, scipy 1.7.1).

> Often these problems are caused by an installation that required an incompatible downgrade due to a secondary requirement (e.g. opencv is often.a culprit) that the package manager didn't catch. If you install from scratch into a new conda environment or venv, do you still get the problem?

I can try to install everything into a new empty conda environment. So far on the computer that runs our Nion microscope, I have been cloning the existing anaconda environment, then install the packages I need on top of that. I wonder if I start from a new conda environment, maybe I won't be able to install the nion-alignment and Nion-Hardware package, then the Swift I installed in the new environment won't be able to connect to the microscope?

Besides, I have tried to install Swift on a Windows system, with exactly the same setup as my Linux system. I can import gpytorch in the python console in Swift with no problem.

**Comment by cmeyer** [comment] 2021-10-16 15:43
Next question, what command are you using to install `gpytorch`? It is not a standard Anaconda package. Are you installing from PyPI? Or perhaps `conda-forge`?

**Comment by cmeyer** [comment] 2021-10-16 16:24
Some experiments:

The following command fails, meaning that `gpytorch` is not a standard Anaconda install.

`conda create -n xyz gpytorch`

Also, if I run (`pytorch` being a prerequisite for `gpytorch`):

`conda create -n xyz pytorch`

Anaconda tries to create an environment with Python 3.7. Given these reductive cases, neither of these  are probably going to work with the standard microscope installation of Swift.

As an alternative, from the standard installation, I had success using

`pip install gpytorch`

However, I'm not sure if this will cause problems down the road due to library conflicts - since Anaconda doesn't support this directly, I wouldn't make any guarantees about it.

Also, it might be tempting to mix in `conda-forge` packages on the standard microscope installation of Swift. This is not recommended (or supported) and will lead to either performance issues or library compatibility issues (crashes).

In any case, I emailed you the "standard microscope installation commands" separately if you need to experiment and recreate that environment.

**Comment by cmeyer** [comment] 2021-10-29 20:33
Yes let's close it for now.

**Closed by cmeyer** 2021-10-29 20:33 UTC
