### ISSUE TITLE
Exporting multiple data items should report failures if any occur

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#749] opened 2021-10-21 01:59 UTC
Exporting a batch of files is complicated and may result in failures of individual items due to combinations of data types and file formats. While this might be reported by individual notifications, it would be nice to have a consolidated window showing each exported item in a table, each item's progress, each item's final status (succeeded, failed, maybe specific notes), and each item's final name and location with a button to open its file folder.

Try to export an image and a composite line plot to ndata. The image will export. The composite line plot will silently fail.
```[tasklist]
### Tasks
- [ ] https://github.com/nion-software/nionswift/issues/630
- [ ] https://github.com/nion-software/nionswift/issues/245
```

**Comment by jamesrussell216** [comment] 2024-05-21 13:06
@cmeyer is this specific to an image and composite line plot or more generally? We've noticed that if you do some combination of exports and file format sometimes you just don't get a file for particular combinations - is that by design if you have invalid combination?

**Comment by Ion-e** [comment] 2024-06-19 12:40
Seeing that it's not addressed in #1072, Should unvalid formats be disabled/removed in the dropdown selection when there is not an expected valid export to happen? (i.e: PNG export on a 2D ramp).

**Closed** 2024-06-19 16:13 UTC
Labels: type - bug, impact - critical, good first issue, f - user-interface, f - IO, audience - user, effort - day, reach - small

**Comment by Ion-e** [comment] 2024-07-02 12:02
#630 hasn't been addressed.

**Comment by cmeyer** [comment] 2024-07-02 17:19
I removed it from the task list. This issue is closed - file new bugs if you encounter one. Thanks!

**Comment by Ion-e** [comment] 2024-07-04 14:46
Issue verified as implemented.

Thank you!
