### ISSUE TITLE
Provide different options for how to show dimensional calibrations.

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#396] opened 2020-05-04 16:12 UTC
For example axes with ticks and labels can be useful for data that has different calibration in x- and y-direction.
See matplotlib figures as an example:
![grafik](https://user-images.githubusercontent.com/16721195/80987757-caca8380-8e32-11ea-9df5-6525599dfd2e.png)

**Comment by cmeyer** [comment] 2020-05-04 16:26
Duplicate of #46

**Closed** 2020-05-04 16:27 UTC
