### ISSUE TITLE
Line profile on multiples images

### ISSUE THREAD

**Issue by yiranlus** [nion-software/nionswift#782] opened 2021-12-21 16:44 UTC
Is it possible to use the same line profile on different images so that intensity on different images at the same positions can be compared? It would be good if all line regions kept their positions updated with each other when I am exploring the data. 

```[tasklist]
### Tasks
- [ ] https://github.com/nion-software/nionswift/issues/548
```

**Comment by cmeyer** [comment] 2021-12-21 20:57
Thanks for this request. Unfortunately this is not possible right now - but we've also been wanting this for a while, too.

Some related items that need to be done:
- [ ] #548 
- [ ] #113 
- [ ] #178

**Comment by cmeyer** [comment] 2024-02-27 03:40
BPS Comment from 2024-02-06:

Copying line profile parameters from one image to another.

This may sound like a small or specialized thing. but it comes up all the time. There is a technical workaround to make the same line profile on two images, but it is very tedious, and it becomes practically unworkable as the number of data items you want to compare goes up.

I really want to emphasize this one. Having a quick workflow for this would be huge.

It could be as simple as being able to copy all the line profile parameters at once from the inspector, and paste them all at once into the inspector for another line profile.

I think the ideal workflow would be that if you select and ctrl V a line profile graphic, and paste it onto another data item, it should automatically create the same line profile on the new data item if the dimensions are compatible.

**Comment by kociak** [comment] 2024-02-27 07:44
I am not sure it is the right issue for that but having mirrored elements, such as ROI ( especially pick tools for SI) is in general something needed. The practical case for SI is browsing an HAADF with a pick tool and having the corresponding spectrum from the corresponding SI updated. Same between ie two or more SI, those SI being for example raw and data analyses versions of the raw one. In our lab we keep talking about this feature again and again ...

**Comment by cmeyer** [comment] 2024-02-27 16:11
Moving main discussion of mirroring graphics to #548

**Comment by cmeyer** [comment] 2024-02-27 16:14
Closing as duplicate of #548

**Closed by cmeyer** 2024-02-27 16:14 UTC
Labels: type - enhancement, needs planning, impact - critical, f - user-interface, f - line-profile, f - graphics, f - displays, audience - user, reach - large, effort - few weeks
