### ISSUE TITLE
Live computations get recalculated unnecessarily when upstream data item is touched

### ISSUE THREAD

**Issue by bentps** [nion-software/nionswift#948] opened 2023-04-06 18:56 UTC
Put succinctly: chains of live computations are often inappropriately triggered to recompute.

For example, say I have a data item A with a sequence dimension that is the source data for "measure shifts". The shifts are then used to create an aligned version of the original data item (and perhaps to align many other data items B, C, etc). If I use the scroll bar to change the displayed frame of the sequence of data item A, it will trigger a re-computation of the shifts, which triggers re-computations of all downstream alignments. Depending on the size of data items A, B, C, etc, just trying to scroll through data item A can trigger minutes of unwanted re-computations.

**Comment by cmeyer** [comment] 2023-11-02 18:42
Duplicate of #147

**Closed by cmeyer** 2023-11-02 18:42 UTC
