### ISSUE TITLE
Make export dialog behave similarly for a single window vs. multiple

### ISSUE THREAD

**Issue by tylerharvey** [nion-software/nionswift#932] opened 2023-01-18 22:19 UTC
This dialog window is only available for multiple-window export.
![image](https://user-images.githubusercontent.com/13757333/213307544-9887b746-86fa-47c7-ad34-059f3d71b2e5.png)
I can see design reasons for this, but for consistency of use it would be really nice to also have the same export options for single-window export. At the moment, for consistent naming, a user must make sure to always export multiple windows.

**Comment by bentps** [comment] 2023-04-10 19:46
I want to second this request. In addition to the dialog window options being available, the multi-data-item export puts dashes between the words of the data item title, while exporting a single data item uses spaces.

**Comment by jamesrussell216** [comment] 2024-06-14 10:40
@KRLango is going to start working on this one now. Just defining a few bits for prosperity...

- In moving the single item export code over to work off the multi item export, as @bentps says that will lead to single items exporting with the multi item export naming convention. Which as far as I can see is probably a good thing but I thought I'd explicitly state it unless anyone can see a problem!
- @KRLango is going to "tidy" the UI up a little as well.

**Comment by jamesrussell216** [comment] 2024-06-17 09:06
Fixed by #1070

**Closed by jamesrussell216** 2024-06-17 09:06 UTC
Labels: type - enhancement, good first issue, f - user-interface, f - IO, impact - low, audience - user, effort - day, reach - large

**Comment by Ion-e** [comment] 2024-07-02 10:20
Blocked by https://github.com/nion-software/nion-internal/issues/136

**Comment by jamesrussell216** [comment] 2024-07-03 14:49
So I'd argue @Ion-e that #136 is an extension on the original spec for this - a worth while one, but an extension none the less, so I'd further argue if the feature is otherwise working as intended this is completed and we'll add #136 to the to do pile?

**Comment by cmeyer** [comment] 2024-07-03 15:01
This issue is closed. Can you open a discussion for further discussion of unrelated items?

**Comment by jamesrussell216** [comment] 2024-07-03 15:04
It is not an unrelated item and it's a simple question - I don't think it needs a discussion item.

**Comment by Ion-e** [comment] 2024-07-04 14:46
Verified as implemented, thank you!
