### ISSUE TITLE
Errors in computation's execute are not passed to the main thread

### ISSUE THREAD

**Issue by kociak** [nion-software/nionswift#781] opened 2021-12-21 11:42 UTC
In a computation, a runtime error is not caught if triggered from `execute`, but is in e.g `commit`.
My guess is that `execute` does not run in the main thread, so the `exceptions` are not carried over to the main thread.
It is annoying to debug when coding, but more importantly to report to the user for day to day usage.
Maybe at least the problem should be documented for coders, and maybe a strategy could be proposed for telling the user something went wrong (like incitating the coder to make a `try... except` with a `print` statement in the `except`part?

**Comment by cmeyer** [comment] 2021-12-22 23:23
This is a duplicate of #577 . I'm closing this one in favor of the older issue.

Also, please note that adding computations from packages is still not officially supported and we expect the interface to [change significantly](https://github.com/nion-software/nionswift/issues/320) #320 in the coming months. We'll try to maintain backwards compatibility for at least one version after an officially supported version is released; but it may require maintenance on your part.

**Closed by cmeyer** 2021-12-22 23:23 UTC
